<script type="text/javascript" src="../../js/jquery-3.6.0.min.js"></script>
<script type="text/javascript" src="../../resources/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="../../js/validation.js"></script>
<script type="text/javascript" src="../../resources/sweetalert.js"></script>
<script type="text/javascript" src="../../resources/toastr/build/toastr.min.js"></script>
<script type="text/javascript" src="../../resources/fontawesome/js/all.min.js"></script>
<script type="text/javascript" src="../../resources/DataTables/datatables.min.js"></script>
<script type="text/javascript" src="../../js/script.js"></script>
<script type="text/javascript" src="../../resources/fusioncharts/js/fusioncharts.js"></script>
<script type="text/javascript" src="../../resources/fusioncharts/js/themes/fusioncharts.theme.fusion.js"></script>
<script type="text/javascript" src="../../js/chart.js"></script>
<script type="text/javascript" src="../../js/route.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/apexcharts"></script>